name: rarbg_api
description: A new Flutter package project.
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  dio: ^5.3.2
  dio_smart_retry: ^5.0.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints:
    git: https://github.com/Sockitos/flutter_lints/
  freezed: ^2.4.2
  json_serializable: ^6.7.1
